name: CI

on: 
  push:

jobs:
  ci:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_v8.yml
          name: v8_bin
          path: unity/native_src/
      - name: Build plugin
        run: |
          md unity\general\Bin
          cd unity\native_src
          .\make_win64.bat
          copy build64\Release\puerts.dll ..\general\Bin
          dir ..\general\Bin
      - name: UnitTest
        run: |
          cd unity\general\vs2013
          nuget restore Puerts.sln
          nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner -ExcludeVersion
          msbuild /property:Configuration=Release Puerts.sln
          ./testrunner/NUnit.ConsoleRunner/tools/nunit3-console.exe ../Bin/Puerts.UnitTest.dll
